/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xxx_media_Media */

#ifndef _Included_com_xxx_media_Media
#define _Included_com_xxx_media_Media
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xxx_media_Media
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_xxx_media_Media_render
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_xxx_media_Media
 * Method:    playSound
 * Signature: (Lcom/xxx/media/MusicPlay;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xxx_media_Media_playSound
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
